apiVersion: apps/v1
kind: Deployment
metadata:
  name: cga-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cga-db
  template:
    metadata:
      labels:
        app: cga-db
    spec:
      containers:
        - name: cga-db
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cga-app-config
                  key: Database__Name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cga-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cga-postgres-secret
                  key: password
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
