apiVersion: apps/v1
kind: Deployment
metadata:
  name: cga-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cga-app
  template:
    metadata:
      labels:
        app: cga-app
    spec:
      containers:
        - name: cga-app
          image: ghcr.io/jossuel55/cga-jenkins/cga-app@sha256:e98d34338c1b000cd25271a9ed3e77edf5eea3b75aaf7c3c8996ada9f850f9b2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: cga-app-config
          env:
            - name: Database__Username
              valueFrom:
                secretKeyRef:
                  name: cga-postgres-secret
                  key: username
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: cga-postgres-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
